# headers and icon 
title: Tashi Tengyal
info: CS @ Seoul National University. Applied NLP @ Rezi.ai
icon-pic: assets/profile.jpg

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md